config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
end

app/models/user.rb
# User Model
class User < ActiveRecord::Base
  include ElasticSearchable
  include ActivityHistory

  before_save :create_permalink, if: :new_record?
  rolify
  validates_presence_of :name, :role_ids, :email

  # has_many :posts, dependent: :destroy relation posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def rol
    roles.first.name
  end

  def self.query(query)
    { query: { multi_match: {
      query: query,
      fields: [:rol, :name, :email, :id],
      operator: :and,
      lenient: true }
    }, sort: { id: 'desc' }, size: count }
  end

  # Get the page number that the object belongs to
  def page(order = :id)
    ((self.class.order(order => :desc)
      .pluck(order).index(send(order)) + 1)
        .to_f / self.class.default_per_page).ceil
  end

  # Build index elasticsearch
  def as_indexed_json(_options = {})
    as_json(
      only: [:id, :name, :email],
      methods: [:rol]
    )
  end

  private

  def create_permalink
    self.permalink = name.downcase.parameterize + '-' + SecureRandom.hex(4)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  # UsersController
  class UsersController < AdminController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    def index
      users = User.searching(@query).where('id != ?', current_user.id)
      @objects = users.page(@current_page)
      @total = users.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to users_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    def new
      @user = User.new
    end

    def show
    end

    def edit
    end

    def update
      update_attributes = user_params.delete_if do |_, value|
        value.blank?
      end

      if @user.update_attributes(update_attributes)
        redirect(@user, params)
      else
        render action: 'edit'
      end
    end

    def create
      @user = User.new(user_params)

      if @user.save
        @user.add_role Role.find(user_params.fetch(:role_ids)).name
        redirect(@user, params)
      else
        render action: 'new'
      end
    end

    def destroy
      @user.destroy
      redirect_to admin_users_path, notice: actions_messages(@user)
    end

    def destroy_multiple
      User.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_users_path(page: @current_page, search: @query),
        notice: actions_messages(User.new)
      )
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :name, :email, :password, :password_confirmation,
        :role_ids, :encrypted_password
      )
    end

    def show_history
      get_history(User)
    end

    # Get submit key to redirect, only [:create, :update]
    def redirect(object, commit)
      if commit.key?('_save')
        redirect_to admin_user_path(object), notice: actions_messages(object)
      elsif commit.key?('_add_other')
        redirect_to new_admin_user_path, notice: actions_messages(object)
      elsif commit.key?('_assing_rol')
        redirect_to admin_users_path, notice: actions_messages(object)
      end
    end
  end
end

app/views/admin/users/_description.html.haml
.listing-show-header{ class: "keppler-bg-2" }
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("keppler.models.singularize.user").humanize
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		.collection.with-header
			.collection-header
				%h5.center-align
					= @activities.empty? ? t('keppler.messages.no_events') : t("keppler.titles.history")
			- @activities.each do |activity|
				- if activity.trackable_type.eql? "Session"
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: "name" }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: "name" }

app/views/admin/users/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_users_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @user] do |f|
						.row
							= f.input :name
							= f.input :email
							= f.input :role_ids, collection: Role.all.map { |rol| [rol.name.humanize, rol.id] }, label: false, include_blank: t("keppler.actions.select_rol"), input_html: { class: "browser-default" }
							= f.input :password
							= f.input :password_confirmation
							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: "_save"
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: "_add_other"

app/views/admin/users/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, User
			= link_to "#modal-#{@user.id}", class: "btn-floating waves-effect waves-light btn-flat tooltipped modal-trigger", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.change_rol")  do
				= material_icon.md_24.supervisor_account
		- if can? :update, User
			= link_to edit_admin_user_path(@user), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("keppler.models.singularize.user").humanize
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			- @user.as_json(only: ["id", "name", "permalink", "email", "created_at", "sign_in_count", "updated_at", "password"]).each do |attribute, value|
				%li.list-row
					.display-label= t("activerecord.attributes.user.#{attribute}")
					.display-value= value
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_users_path

= render "admin/users/modal"

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/users/_listing.html.haml
%tr{ id: "row-#{user.id}" }
	- if can? :destroy_multiple, User
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_user_path(user), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{user.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{user.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{user.id}" }
	%td.hide-on-small-and-down{style:"width: 30%"}
		= link_to "", admin_user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.name
	%td{style:"width: 35%"}
		= link_to "", admin_user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.email
	%td.hide-on-small-and-down{style:"width: 20%"}
		= link_to "", admin_user_path(user, search: @query), remote: true, class: "show-row"
		%span
			= user.rol.humanize
	%td{style:"width: 5%"}
		= link_to admin_user_path(user), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/users/_modal.html.haml
.modal{ id: "modal-#{@user.id}"}
	= form_tag admin_user_path(@user),  method: "PUT" do
		.modal-header
			%h4= "#{t('keppler.actions.change_rol')} - #{@user.name}"
		.modal-content
			- Role.all.each do |role|
				.radio-button
					= radio_button_tag "user[role_ids]", role.id, false, class: "radio-button__input", id: "radio#{role.id}", :type => "radio", :value => "#{role.id}", :checked => @user.has_role?(role.name)
					= label_tag "user[role_ids]", role.name.humanize, class: "radio-button__label", :for => "radio#{role.id}"
		.modal-footer
			.actions
				= button_tag t('keppler.actions.assign_rol'), :class => "waves-effect waves-light btn", name: '_assing_rol'
				= link_to t('keppler.actions.cancel'), "", class: "modal-action modal-close waves-effect waves-light btn red", style: "margin-right:10px;"

app/views/admin/users/edit.html.haml
= title(t('keppler.titles.edit', model: "Users"))
= render 'form'

app/views/admin/users/index.html.haml
= title(t('keppler.titles.index', model: "Users"))

.listing.col.l9.m12.s12
	= link_to new_admin_user_path, class: "btn-add btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
		= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |user|
				= render 'listing', user: user
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.user"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"


= link_to new_admin_user_path, class: "btn-add btn-index-add btn-floating btn-large waves-effect waves-light" do
	= material_icon.md_24.add.css_class("md-light")

app/views/admin/users/new.html.haml
= title(t('keppler.titles.new', model: "Users"))
= render 'form'

app/views/admin/users/show.html.haml
= title(t('keppler.titles.show', model: "Users"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, User
				= link_to admin_user_path(@user), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, User
				= link_to edit_admin_user_path(@user), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_users_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					- @user.as_json(only: ["id", "name", "permalink", "email","created_at", "sign_in_count", "updated_at", "password"], methods: [:rol]).each do |attribute, value|
						%li.list-row
							.display-label= t("activerecord.attributes.user.#{attribute}")
							.display-value.fs-body-1.tc-black-2= value.to_s.humanize

app/views/admin/users/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@user.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");